name: Test Pairwise Compare

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run-tests:

    runs-on: ubuntu-latest


    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]


    steps:
    - name: Checkout code with submodules
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Poetry
      run: |
        python -m pip install --user poetry
        export PATH="$HOME/.local/bin:$PATH"

    - name: Install dependencies with Poetry
      run: |
        poetry install --no-interaction

    - name: Test with pytest
      run: |
        poetry run pytest
      working-directory: ${{ github.workspace }}
